apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop_top-level
    tier: app-shipping
data:
  CART_ENDPOINT: "cart-service:8080"
  DB_HOST: "mysql"