apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
  labels:
    component: catalogue-svc
    project: roboshop-svc
    tier: app-catalogue-svc
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app-catalogue
  ports: 
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port