apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  labels:
    purpose: demo
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
data:
  username: "YWRtaW4="
  password: "YWRtaW4xMjM="