apiVersion: v1
kind: Pod 
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity-1
spec: 
  containers:
  - name: nginx-1
    image: nginx

---

apiVersion: v1
kind: Pod 
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-affinity-2
spec: 
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx-2
    image: nginx



# apiVersion: v1
# kind: Pod
# metadata:
#   name: with-pod-affinity
# spec:
#   affinity:
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: security
#             operator: In
#             values:
#             - S1
#         topologyKey: topology.kubernetes.io/zone
#     # podAntiAffinity:
#     #   preferredDuringSchedulingIgnoredDuringExecution:
#     #   - weight: 100
#     #     podAffinityTerm:
#     #       labelSelector:
#     #         matchExpressions:
#     #         - key: security
#     #           operator: In
#     #           values:
#     #           - S2
#     #       topologyKey: topology.kubernetes.io/zone
#   containers:
#   - name: with-pod-affinity
#     image: nginx
