apiVersion: v1
kind: Pod 
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-anti-affinity-1
spec: 
  containers:
  - name: nginx-1
    image: nginx

---

apiVersion: v1
kind: Pod 
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-anti-affinity-2
spec: 
  affinity:
    podAntiAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      # - labelSelector:
      #     matchExpressions:
      #     - key: app-name
      #       operator: In
      #       values:
      #       - pod-1
      #   topologyKey: topology.kubernetes.io/zone
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app-nameee
              operator: In
              values:
              - pod-1
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx-2
    image: nginx