apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: roboshop
  labels:
    component: frontend-svc
    project: roboshop-svc
    tier: web-frontend-svc
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
    tier: web-frontend
  ports: 
    - protocol: TCP
      port: 80 # service port
      targetPort: 8080 # container port