apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    component: redis-headless-svc
    project: roboshop-headless-svc
    tier: database-headless-svc
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port