apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    component: mysql-secret
    project: roboshop_top-level_secret
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="