apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    component: mysql-headless-svc
    project: roboshop-headless-svc
    tier: database-headless-svc
spec:
  clusterIP: None
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port