apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql-svc
    project: roboshop-svc
    tier: database-svc
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port