apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  labels:
    component: payment-secret
    project: roboshop_top-level_secret
    tier: database
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="