apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    component: rabbitmq-secret
    project: roboshop_top-level_secret
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    component: rabbitmq-headless-svc
    project: roboshop-headless-svc
    tier: database-headless-svc
spec:
  clusterIP: None
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq-svc
    project: roboshop-svc
    tier: database-svc
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq_top-level
    project: roboshop_top-level
    tier: database_top-level
spec:
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless" # this should be service name
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: rabbitmq  # has to match .spec.selector.matchLabels
        project: roboshop
        tier: database 
    spec:
      containers:
      - name: rabbitmq
        image: charan466/rabbitmq:v1
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name:  rabbitmq-data
          mountPath: /var/lib/rabbitmq
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-dynamic"
      resources:
        requests:
          storage: 3Gi

