apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    component: rabbitmq-secret
    project: roboshop_top-level_secret
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="