apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq-svc
    project: roboshop-svc
    tier: database-svc
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port