apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    component: rabbitmq-headless-svc
    project: roboshop-headless-svc
    tier: database-headless-svc
spec:
  clusterIP: None
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port