apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq_top-level
    project: roboshop_top-level
    tier: database_top-level
spec:
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless" # this should be service name
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  template:
    metadata:
      labels:
        component: rabbitmq  # has to match .spec.selector.matchLabels
        project: roboshop
        tier: database 
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.statefulset.imageURL }}:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name:  rabbitmq-data
          mountPath: /var/lib/rabbitmq
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-dynamic"
      resources:
        requests:
          storage: 3Gi