apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  namespace: roboshop
  labels:
    component: cart
    project: roboshop_top-level
    tier: app-cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue-service"
  CATALOGUE_PORT: "8080"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: roboshop
  # deployment labels, these belong to the deployment itself, not the Pods.
  labels:
    component: cart
    project: roboshop_top-level
    tier: app-cart
    # These labels identify and organize the ReplicaSet resource itself.
    # Used by carts or tools to filter ReplicaSets, search, and group resources. (e.g., kubectl get all -l project=roboshop_top-level (or) kubectl get rs -l project=roboshop_top-level).
    # Not used by ReplicaSet controller to create or manage Pods.
spec:
  replicas: 1
  selector:
    matchLabels: # Tells ReplicaSet which Pods to manage
      component: cart
      project: roboshop
      tier: app-cart
      # These labels define which Pods the ReplicaSet should watch and manage.
      # If any Pod in the cluster matches these labels, the ReplicaSet counts them toward its replica count.
      # This selector must exactly match the template labels so the RS can manage the Pods it creates.
  template:
    metadata: # Labels for the Pods it creates
      labels: 
        component: cart
        project: roboshop
        tier: app-cart
        # These labels are app-cartlied to new Pods created by the ReplicaSet.
        # They should match the selector labels so the ReplicaSet can identify and manage these Pods.
        # If they don’t match, the RS will never associate with the Pods it creates, causing errors or orphan Pods.
    spec:
      containers:
      - name: cart
        image: charan466/cart:v1
        envFrom:
        - configMapRef:
            name: cart-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: roboshop
  labels:
    component: cart-svc
    project: roboshop-svc
    tier: app-cart-svc
spec:
  selector:
    component: cart
    project: roboshop
    tier: app-cart
  ports: 
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port

